// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKgmQWar9Xta0J-zynE9yNC9rlkFWDNv4',
    appId: '1:865934151754:web:73fe38488039490bb0d6b3',
    messagingSenderId: '865934151754',
    projectId: 'congressionalac',
    authDomain: 'congressionalac.firebaseapp.com',
    storageBucket: 'congressionalac.appspot.com',
    measurementId: 'G-YW2GQDYSPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4aibRvu0EMsh49Z3cCUTswnXzhuWW3O0',
    appId: '1:865934151754:android:f00ee42c55480de3b0d6b3',
    messagingSenderId: '865934151754',
    projectId: 'congressionalac',
    storageBucket: 'congressionalac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDueIIRjNWdAEvf9v_ehlFlfOHFsvuLoTw',
    appId: '1:865934151754:ios:4416d98958b84516b0d6b3',
    messagingSenderId: '865934151754',
    projectId: 'congressionalac',
    storageBucket: 'congressionalac.appspot.com',
    iosClientId: '865934151754-sn47s5b5f75ud8p71ubal9c5q5gic1s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.congressionalappchallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDueIIRjNWdAEvf9v_ehlFlfOHFsvuLoTw',
    appId: '1:865934151754:ios:e86441b150145902b0d6b3',
    messagingSenderId: '865934151754',
    projectId: 'congressionalac',
    storageBucket: 'congressionalac.appspot.com',
    iosClientId: '865934151754-f66578sss64mkutla0st6ogilp0ps7ie.apps.googleusercontent.com',
    iosBundleId: 'com.example.congressionalappchallenge.RunnerTests',
  );
}
